version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_vol:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: 123456aA#*
       MYSQL_DATABASE: jwt
       MYSQL_USER: amani
       MYSQL_PASSWORD: 123456aA#*
     ports:
       - 3307:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456aA#*
   web:
    build:
      context: .
    depends_on:
      - db
    image: tomcat:8.5.0
    volumes:
      - ./target/LoginWebApp-1.war:/usr/local/tomcat/webapps/LoginWebApp-1.war
    ports:
      - '8086:8080'
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA#*
      MYSQL_DATABASE: jwt
      MYSQL_USER: amani
      MYSQL_PASSWORD: 123456aA#*
volumes:
    db_vol:
